# Generated by Django 5.0.4 on 2024-04-23 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wager', '0003_alter_wager_stake'),
    ]

    operations = [
        migrations.AddField(
            model_name='sport',
            name='key',
            field=models.CharField(default='key', max_length=255),
        ),
    ]
