# Generated by Django 5.0.4 on 2024-04-22 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('event', models.CharField(max_length=255)),
                ('stake', models.FloatField()),
                ('odds', models.FloatField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='wager_images')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wagers', to='wager.sport')),
            ],
        ),
    ]
