# Generated by Django 5.0.4 on 2024-04-22 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wager', '0002_wager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wager',
            name='stake',
            field=models.IntegerField(),
        ),
    ]
